### ISSUE TITLE
Are Dependencies needed?

### ISSUE THREAD

**Issue by Redstonerayy** [alexcoder04/linux-dotfiles#1]
After cloning the repo and invoking the install script for the i3 wm it reports errors in line 84,84 and 120 or so saying that it expected a different token. It also shows a red error message that dependencies are missing. Which dependencies to i need or how can i fix this error?

**Comment by alexcoder04** [comment]
As it says in the README, this repo is not ment for public use, because of poor documentation and the install system which is tuned for my specifical machines.
You are free to take inspiration from it or use parts of the config files, but in this case you have to take a careful look at it to make sure you understand how it works.
